export default {
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_LARGE: 18,
    FONT_SIZE_TITLE: 30,
    PRIMARY_COLOR: '#001A70',
    SECONDARY_COLOR: '#FE5815',
    FONT_WEIGHT_LIGHT: 200,
    FONT_WEIGHT_MEDIUM: 600,
    FONT_WEIGHT_HEAVY: 800,
    FONT_FAMILY: 'sans-serif',
  };